languages:
   Ruby: true
   JavaScript: true
exclude_paths:
- frontend/www/lib/**/*
- bower_components/angular/angular.js
- bower_components/angular/angular.min.js
- coverage/assets/0.10.0/application.js
